"use client";

import React, { useState, useRef, useEffect } from "react";
import { useApi } from "@/hooks/useApi";
import { 
  Mic, 
  Video, 
  VideoOff, 
  StopCircle, 
  Play, 
  Loader2, 
  ShieldAlert, 
  CheckCircle,
  Activity,
  Award,
  ArrowRight
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export default function MockInterview() {
  const { call } = useApi();
  const [isStarted, setIsStarted] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  
  const [proctoringScore, setProctoringScore] = useState(100);
  const [feedback, setFeedback] = useState<string>("");
  const [messages, setMessages] = useState<any[]>([]);
  const [finalReport, setFinalReport] = useState<any>(null);

  const videoRef = useRef<HTMLVideoElement>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);

  // Resume & JD for context
  const [resumeText, setResumeText] = useState("");
  const [jobDescription, setJobDescription] = useState("");

  useEffect(() => {
    if (isStarted) {
      startCamera();
    }
  }, [isStarted]);

  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
    } catch (err) {
      console.error("Camera error:", err);
    }
  };

  const startTurn = () => {
    audioChunksRef.current = [];
    setIsRecording(true);
    
    // Start recording audio
    const stream = (videoRef.current?.srcObject as MediaStream);
    const mediaRecorder = new MediaRecorder(stream);
    mediaRecorderRef.current = mediaRecorder;
    
    mediaRecorder.ondataavailable = (e) => {
      audioChunksRef.current.push(e.data);
    };
    
    mediaRecorder.onstop = processTurn;
    mediaRecorder.start();
  };

  const stopTurn = () => {
    mediaRecorderRef.current?.stop();
    setIsRecording(false);
  };

  const processTurn = async () => {
    setIsLoading(true);
    const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' });
    
    // Capture frame from video
    const canvas = document.createElement("canvas");
    canvas.width = videoRef.current?.videoWidth || 640;
    canvas.height = videoRef.current?.videoHeight || 480;
    canvas.getContext("2d")?.drawImage(videoRef.current!, 0, 0);
    const frameBlob = await new Promise<Blob | null>(res => canvas.toBlob(res, 'image/jpeg'));

    const formData = new FormData();
    formData.append("audio", audioBlob);
    if (frameBlob) formData.append("frame", frameBlob);
    formData.append("resumeText", resumeText);
    formData.append("jobDescription", jobDescription);
    formData.append("history", JSON.stringify(messages));

    try {
      const res = await call("/api/ai/interview/turn", {
        method: "POST",
        body: formData
      });

      setMessages(prev => [...prev, { bot: res.nextQuestion }]);
      setProctoringScore(res.proctoringScore);
      setFeedback(res.proctoringFeedback);
      
      // Speak the next question
      speak(res.nextQuestion);
    } catch (err) {
      console.error("Turn process failed:", err);
    } finally {
      setIsLoading(false);
    }
  };

  const speak = (text: string) => {
    const utter = new SpeechSynthesisUtterance(text);
    utter.rate = 1.1;
    utter.pitch = 1.0;
    window.speechSynthesis.speak(utter);
  };

  const finishInterview = async () => {
    setIsLoading(true);
    try {
      const res = await call("/api/ai/interview/final-feedback", {
        method: "POST",
        body: JSON.stringify({ 
           sessionHistory: messages,
           resumeText,
           jobDescription
        })
      });
      setFinalReport(res.report);
    } catch (err) {
      console.error("Final report error:", err);
    } finally {
      setIsLoading(false);
    }
  };

  if (finalReport) {
    return (
        <div className="max-w-4xl mx-auto space-y-8 animate-in zoom-in-95 duration-700">
            <div className="card-glass p-12 text-center space-y-6">
                <div className="w-24 h-24 rounded-full bg-accent-start/10 mx-auto flex items-center justify-center">
                    <Award size={48} className="text-accent-start" />
                </div>
                <h1 className="text-4xl font-black">Interview <span className="gradient-text">Complete</span></h1>
                <p className="text-text-secondary">Your session report has been generated by the neural career engine.</p>
            </div>
            
            <div className="card-glass p-10 prose prose-invert max-w-none prose-sm leading-relaxed whitespace-pre-wrap font-sans text-text-secondary">
                {finalReport}
            </div>
            
            <button 
                onClick={() => window.location.reload()}
                className="btn-primary w-full max-w-xs mx-auto flex items-center justify-center gap-3 cursor-pointer"
            >
                Return to Dashboard <ArrowRight size={20} />
            </button>
        </div>
    );
  }

  return (
    <div className="h-full flex flex-col space-y-8">
      
      {/* Header */}
      <div className="flex justify-between items-start">
        <div className="space-y-1">
            <h1 className="text-3xl font-bold tracking-tight">AI Interview <span className="gradient-text">Room</span></h1>
            <p className="text-text-secondary text-sm">Real-time, proctored AI simulation with professional feedback. Powered by <span className="text-indigo-400 font-bold">GEMINI PRO</span>.</p>
        </div>
        {!isStarted && <button onClick={() => setIsStarted(true)} className="btn-primary px-8 cursor-pointer">Enter Room</button>}
      </div>

      <div className="grid lg:grid-cols-3 gap-8 flex-1 min-h-0">
        
        {/* Left — Video Feed */}
        <div className="lg:col-span-2 space-y-6 flex flex-col">
            <div className="flex-1 card-glass p-0 relative overflow-hidden bg-black flex items-center justify-center shadow-2xl">
                 {!isStarted ? (
                     <div className="text-center p-12 space-y-6">
                         <div className="w-20 h-20 rounded-full bg-hover-bg border border-border-subtle mx-auto flex items-center justify-center">
                            <VideoOff size={32} className="text-text-muted" />
                         </div>
                         <div className="space-y-4 max-w-md mx-auto">
                            <input 
                                placeholder="Paste Job Description..." 
                                className="w-full bg-hover-bg border border-border-subtle rounded-xl p-3 text-sm focus:outline-none" 
                                value={jobDescription}
                                onChange={(e) => setJobDescription(e.target.value)}
                            />
                            <textarea 
                                placeholder="Paste your Resume text for context..." 
                                className="w-full bg-hover-bg border border-border-subtle rounded-xl p-3 h-32 text-sm focus:outline-none"
                                value={resumeText}
                                onChange={(e) => setResumeText(e.target.value)}
                            />
                         </div>
                     </div>
                 ) : (
                     <>
                        <video ref={videoRef} autoPlay muted className="w-full h-full object-cover" />
                        <div className="absolute top-6 left-6 flex items-center gap-3">
                            <div className="px-3 py-1.5 bg-red-500 rounded-lg text-[10px] font-black uppercase text-white tracking-[2px] animate-pulse flex items-center gap-2">
                                <Activity size={12} /> Live Turn
                            </div>
                            <div className="px-3 py-1.5 bg-black/60 backdrop-blur-md border border-border-subtle rounded-lg text-[10px] font-bold text-white tracking-widest uppercase">
                                1080p | Proctored
                            </div>
                        </div>
                        <div className="absolute bottom-6 right-6">
                            <div className="flex items-center gap-2 px-4 py-2 bg-black/60 backdrop-blur-md rounded-xl border border-border-subtle shadow-2xl">
                               <div className={`w-3 h-3 rounded-full ${proctoringScore > 80 ? 'bg-green-500' : 'bg-red-500'} animate-pulse shadow-[0_0_10px_rgba(34,197,94,0.5)]`} />
                               <span className="text-[10px] uppercase font-black text-white tracking-widest">Integrity: {proctoringScore}%</span>
                            </div>
                        </div>
                     </>
                 )}
            </div>

            {/* Controls */}
            <div className="card-glass p-4 flex items-center justify-center gap-6 border-border-subtle">
                {!isStarted ? (
                    <button onClick={() => setIsStarted(true)} className="btn-primary px-10 cursor-pointer">Initialize Interface</button>
                ) : (
                    <>
                        <button 
                            disabled={isLoading}
                            onClick={isRecording ? stopTurn : startTurn} 
                            className={`p-6 rounded-full transition-all active:scale-95 shadow-2xl group ${
                                isRecording ? "bg-red-500 text-white hover:bg-red-600" : "bg-accent-start text-white hover:bg-accent-end"
                            }`}
                        >
                            {isLoading ? <Loader2 size={32} className="animate-spin" /> : isRecording ? <StopCircle size={32} /> : <Mic size={32} />}
                        </button>
                        <button onClick={finishInterview} className="btn-ghost px-8 border border-border-subtle cursor-pointer font-bold uppercase tracking-widest text-[10px]">End Session</button>
                    </>
                )}
            </div>
        </div>

        {/* Right — Proctoring Feedback & Chat */}
        <div className="space-y-6 flex flex-col h-full min-h-0">
             <div className="card-glass p-6 space-y-4 shrink-0">
                <div className="flex items-center gap-2 text-sm font-bold uppercase tracking-[2px] text-accent-start">
                    <ShieldAlert size={18} /> Proctoring Update
                </div>
                <div className="p-4 bg-hover-bg border border-border-subtle rounded-xl text-xs text-text-secondary leading-relaxed">
                    {feedback || "Establishing baseline metrics. Waiting for turn submission..."}
                </div>
             </div>

             <div className="card-glass p-0 flex-1 flex flex-col min-h-0 overflow-hidden">
                <div className="p-4 border-b border-border-subtle flex items-center justify-between">
                    <span className="text-sm font-bold uppercase tracking-widest flex items-center gap-2">
                        <CheckCircle size={16} className="text-green-500" /> Interaction Log
                    </span>
                </div>
                <div className="flex-1 overflow-y-auto p-6 space-y-4">
                     {messages.length === 0 ? (
                         <div className="h-full flex flex-col items-center justify-center text-center opacity-30">
                            <Activity size={32} className="mb-4" />
                            <p className="text-xs">Your interaction history will appear here in real-time.</p>
                         </div>
                     ) : (
                         messages.map((m, i) => (
                             <motion.div initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} key={i} className="p-4 bg-hover-bg border border-border-subtle rounded-2xl text-xs text-text-secondary">
                                <span className="font-bold text-accent-start uppercase text-[10px] block mb-1">Interviewer</span>
                                {m.bot}
                             </motion.div>
                         ))
                     )}
                     {isLoading && (
                         <div className="flex items-center gap-3 animate-pulse">
                             <div className="w-2 h-2 rounded-full bg-accent-start" />
                             <span className="text-[10px] uppercase font-bold text-text-muted">AI is thinking...</span>
                         </div>
                     )}
                </div>
             </div>
        </div>

      </div>

    </div>
  );
}
