import React, { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'en' | 'hi' | 'gu';

const translations = {
  en: {
    appName: 'Rakshak AI Learn',
    tagline: 'Next-Gen AI Learning',
    subtitle: 'Multilingual, Offline, Intelligent. Experience an education platform designed for the aspirant.',
    startLearning: 'Start Learning',
    tryDoubtSolver: 'Try AI Doubt Solver',
    coreIntelligence: 'Core Intelligence',
    features: 'Features',
    multimodalTitle: 'Multimodal AI Learning',
    multimodalDesc: 'Ask using text, images, or voice. Our AI understands multiple input formats across 15+ languages simultaneously.',
    doubtSolverTitle: 'Real-Time Doubt Solver',
    doubtSolverDesc: 'Never wait 45 minutes for a sir to reply. Ask now, get AI answers in seconds with step-by-step details.',
    offlineTitle: 'Works Even Offline',
    offlineDesc: 'Our PWA caches lessons locally. Keep learning on your phone even without internet. Zero excuses.',
    chatPlaceholder: 'Ask anything...',
    send: 'Send',
    explainSimpler: 'Explain Simpler',
    translate: 'Translate',
    startCall: 'Start Call',
    end: 'End',
    liveReady: 'LIVE SYSTEM READY',
    aiAvatar: 'AI Avatar',
    experiencePulse: 'Experience the Pulse',
    learnMode: 'Learn',
    chatMode: 'Chat',
    curriculum: 'Curriculum',
    profile: 'Profile',
    generateNotes: 'Generate Notes',
    topicPlaceholder: 'Enter topic or subject...',
    notes: 'Notes',
    quiz: 'Quiz',
    feedback: 'Feedback',
    grade: 'Grade',
    state: 'State',
    generate: 'Generate',
    language: 'Language',
    apiKey: 'Gemini API Key',
    apiKeyPlaceholder: 'Enter your API key...',
    saveKey: 'Save Key',
    installApp: '📲 Install App',
    explainLike10: "Explain Like I'm 10",
    readyToEvolve: 'Ready to evolve your intelligence?',
    joinThousands: 'Join thousands who are learning smarter with Rakshak AI.',
    getFullAccess: 'Get Full Access',
    docs: 'Docs',
    community: 'Community',
    privacyPolicy: 'Privacy Policy',
    loading: 'Thinking...',
    textIntelligence: 'Text Intelligence',
    liveAIAssistant: 'Live AI Assistant',
    complexFormulas: 'Complex Formulas',
    complexFormulasDesc: 'Solve advanced calculus',
    codeReview: 'Code Review',
    codeReviewDesc: 'Debug Python scripts',
    selectGrade: 'Select Grade',
    selectState: 'Select State',
    seventh: '7th Grade',
    eighth: '8th Grade',
    maharashtra: 'Maharashtra',
    assam: 'Assam',
    subjects: 'Subjects',
    topics: 'Topics',
    aiTyping: 'AI is typing',
    voiceInput: 'Voice Input',
    textToSpeech: 'Read Aloud',
    settings: 'Settings',
    version: 'Version 1.0.0',
    footerTagline: 'Democratizing education with AI',
  },
  hi: {
    appName: 'Rakshak AI Learn',
    tagline: 'अगली पीढ़ी की AI शिक्षा',
    subtitle: 'बहुभाषी, ऑफलाइन, बुद्धिमान। एक शिक्षा मंच जो आकांक्षी के लिए बनाया गया है।',
    startLearning: 'सीखना शुरू करें',
    tryDoubtSolver: 'AI डाउट सॉल्वर आज़माएं',
    coreIntelligence: 'मुख्य बुद्धिमत्ता',
    features: 'विशेषताएं',
    multimodalTitle: 'मल्टीमॉडल AI शिक्षा',
    multimodalDesc: 'टेक्स्ट, इमेज, या आवाज़ से पूछें। हमारा AI 15+ भाषाओं में समझता है।',
    doubtSolverTitle: 'रियल-टाइम डाउट सॉल्वर',
    doubtSolverDesc: 'अब सेकंड में AI उत्तर पाएं, कदम-दर-कदम विवरण के साथ।',
    offlineTitle: 'ऑफलाइन भी काम करता है',
    offlineDesc: 'हमारा PWA पाठ स्थानीय रूप से कैश करता है। बिना इंटरनेट के भी सीखें।',
    chatPlaceholder: 'कुछ भी पूछें...',
    send: 'भेजें',
    explainSimpler: 'सरल बताएं',
    translate: 'अनुवाद',
    startCall: 'कॉल शुरू करें',
    end: 'समाप्त',
    liveReady: 'लाइव सिस्टम तैयार',
    aiAvatar: 'AI अवतार',
    experiencePulse: 'अनुभव करें',
    learnMode: 'सीखें',
    chatMode: 'चैट',
    curriculum: 'पाठ्यक्रम',
    profile: 'प्रोफ़ाइल',
    generateNotes: 'नोट्स बनाएं',
    topicPlaceholder: 'विषय या टॉपिक दर्ज करें...',
    notes: 'नोट्स',
    quiz: 'क्विज़',
    feedback: 'फ़ीडबैक',
    grade: 'कक्षा',
    state: 'राज्य',
    generate: 'बनाएं',
    language: 'भाषा',
    apiKey: 'Gemini API Key',
    apiKeyPlaceholder: 'API Key दर्ज करें...',
    saveKey: 'सेव करें',
    installApp: '📲 ऐप इंस्टॉल करें',
    explainLike10: 'बच्चे की तरह समझाएं',
    readyToEvolve: 'अपनी बुद्धि विकसित करने के लिए तैयार?',
    joinThousands: 'हजारों लोग Rakshak AI से स्मार्ट तरीके से सीख रहे हैं।',
    getFullAccess: 'पूरी पहुंच पाएं',
    docs: 'डॉक्स',
    community: 'समुदाय',
    privacyPolicy: 'गोपनीयता नीति',
    loading: 'सोच रहा हूं...',
    textIntelligence: 'पाठ बुद्धिमत्ता',
    liveAIAssistant: 'लाइव AI सहायक',
    complexFormulas: 'जटिल सूत्र',
    complexFormulasDesc: 'उन्नत गणना हल करें',
    codeReview: 'कोड समीक्षा',
    codeReviewDesc: 'Python स्क्रिप्ट डीबग करें',
    selectGrade: 'कक्षा चुनें',
    selectState: 'राज्य चुनें',
    seventh: '7वीं कक्षा',
    eighth: '8वीं कक्षा',
    maharashtra: 'महाराष्ट्र',
    assam: 'असम',
    subjects: 'विषय',
    topics: 'टॉपिक',
    aiTyping: 'AI टाइप कर रहा है',
    voiceInput: 'आवाज़ इनपुट',
    textToSpeech: 'पढ़कर सुनाएं',
    settings: 'सेटिंग',
    version: 'संस्करण 1.0.0',
    footerTagline: 'AI से शिक्षा का लोकतंत्रीकरण',
  },
  gu: {
    appName: 'Rakshak AI Learn',
    tagline: 'આગળની પેઢીની AI શિક્ષા',
    subtitle: 'બહુભાષી, ઓફલાઇન, બુદ્ધિશાળી. ઉચ્ચાકાંક્ષી માટે ડિઝાઇન કરેલ શિક્ષણ પ્લેટફોર્મ.',
    startLearning: 'શીખવાનું શરૂ કરો',
    tryDoubtSolver: 'AI ડાઉટ સોલ્વર અજમાવો',
    coreIntelligence: 'મૂળ બુદ્ધિ',
    features: 'વૈશિષ્ટ્યો',
    multimodalTitle: 'મલ્ટીમોડલ AI શિક્ષા',
    multimodalDesc: 'ટેક્સ્ટ, ઇમેજ, અથવા અવાજ વડે પૂછો. અમારી AI 15+ ભાષાઓ સમજે છે.',
    doubtSolverTitle: 'રીયલ-ટાઇમ ડાઉટ સોલ્વર',
    doubtSolverDesc: 'હવે સેકન્ડમાં AI જવાબ મેળવો, પગલું-દર-પગલું વિગત સાથે.',
    offlineTitle: 'ઓફલાઇન પણ કામ કરે',
    offlineDesc: 'અમારા PWA સ્થાનિક રૂપે પાઠ્ય સ્ટોર કરે. ઇન્ટરનેટ વિના શીખો.',
    chatPlaceholder: 'કંઈ પણ પૂછો...',
    send: 'મોકલો',
    explainSimpler: 'સરળ સમજાવો',
    translate: 'અનુવાદ',
    startCall: 'કૉલ શરૂ કરો',
    end: 'સમાપ્ત',
    liveReady: 'લાઇવ સિસ્ટમ તૈયાર',
    aiAvatar: 'AI અવતાર',
    experiencePulse: 'અનુભવ કરો',
    learnMode: 'શીખો',
    chatMode: 'ચેટ',
    curriculum: 'અભ્યાસક્રમ',
    profile: 'પ્રોફાઇલ',
    generateNotes: 'નોટ્સ બનાવો',
    topicPlaceholder: 'વિષય અથવા ટૉપિક દાખલ કરો...',
    notes: 'નોટ્સ',
    quiz: 'ક્વિઝ',
    feedback: 'પ્રતિસાદ',
    grade: 'ધોરણ',
    state: 'રાજ્ય',
    generate: 'બનાવો',
    language: 'ભાષા',
    apiKey: 'Gemini API Key',
    apiKeyPlaceholder: 'API Key દાખલ કરો...',
    saveKey: 'સેવ કરો',
    installApp: '📲 એપ ઇન્સ્ટૉલ કરો',
    explainLike10: 'બાળકની જેમ સમજાવો',
    readyToEvolve: 'તમારી બુદ્ધિ વિકસાવવા તૈયાર છો?',
    joinThousands: 'હજારો લોકો Rakshak AI સાથે સ્માર્ટ રીતે શીખી રહ્યા છે.',
    getFullAccess: 'સંપૂર્ણ ઍક્સેસ મેળવો',
    docs: 'ડૉક્સ',
    community: 'સમુદાય',
    privacyPolicy: 'ગોપનીયતા નીતિ',
    loading: 'વિચારી રહ્યો છું...',
    textIntelligence: 'ટેક્સ્ટ બુદ્ધિ',
    liveAIAssistant: 'લાઇવ AI સહાયક',
    complexFormulas: 'જટિલ સૂત્રો',
    complexFormulasDesc: 'ઉન્નત ગણતરી ઉકેલો',
    codeReview: 'કોડ સમીક્ષા',
    codeReviewDesc: 'Python સ્ક્રિપ્ટ ડીબગ કરો',
    selectGrade: 'ધોરણ પસંદ કરો',
    selectState: 'રાજ્ય પસંદ કરો',
    seventh: '7મું ધોરણ',
    eighth: '8મું ધોરણ',
    maharashtra: 'મહારાષ્ટ્ર',
    assam: 'આસામ',
    subjects: 'વિષયો',
    topics: 'ટૉપિક',
    aiTyping: 'AI ટાઇપ કરી રહ્યો છે',
    voiceInput: 'અવાજ ઇનપુટ',
    textToSpeech: 'વાંચીને સંભળાવો',
    settings: 'સેટિંગ',
    version: 'આવૃત્તિ 1.0.0',
    footerTagline: 'AI સાથે શિક્ષણનું લોકશાહીકરણ',
  },
} as const;

type Translations = typeof translations['en'];

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: translations.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem('rakshak-lang') as Lang) || 'en';
  });

  const handleSetLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem('rakshak-lang', l);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export type { Lang, Translations };
